// TypeScript interface for angel entities
export interface AngelEntity {
  id: number;
  name: string;
  title: string;
  description: string;
  domain: string;
  psalm: string;
  color: string;
  symbol: string;
  invocationGuide: string;
  evocationGuide: string;
  practicalUses: string[];
  meditationGuide: string;
  offerings: string[];
  timing: string;
  tradition?: string;
  category?: string;
  hebrewName?: string;
  planetaryCorrespondence?: string;
}

export const angelicEntities: AngelEntity[] = [
  {
    id: 1,
    name: "Vehuiah",
    title: "The Resurrector",
    description: "Angel of new beginnings and inspiration. Invoke when starting new projects.",
    domain: "Creation, Inspiration",
    psalm: "Psalm 3:3",
    color: "#ff6b6b",
    symbol: "🌅",
    invocationGuide: "1. Light a white candle and face East\n2. Place your hands over your heart\n3. Say: 'Vehuiah, Angel of Divine Will, I call upon your sacred presence'\n4. State your new beginning or creative project\n5. Ask: 'Guide my steps and illuminate my path'\n6. Visualize golden light filling your solar plexus\n7. Thank Vehuiah and extinguish the candle",
    evocationGuide: "Sit in meditation facing East at sunrise. Visualize a golden sunrise on the horizon. As the light grows brighter, feel it entering your crown chakra and filling your entire being with creative energy. Hold this visualization for 10-15 minutes while focusing on your new beginning.",
    practicalUses: ["Starting new projects", "Overcoming creative blocks", "Finding inspiration", "Career changes", "Artistic endeavors"],
    meditationGuide: "Close your eyes and imagine standing at the edge of a cliff at dawn. Feel the cool morning air. Watch as the sun rises, painting the sky in brilliant gold and orange. As the first rays touch your face, feel Vehuiah's inspiring energy flowing into you, filling you with divine creativity and the courage to begin anew.",
    offerings: ["White flowers", "Golden honey", "Sunrise water", "Creative works"],
    timing: "Dawn, Sunday, Spring months",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "והויה",
    planetaryCorrespondence: "Sun"
  },
  {
    id: 2,
    name: "Jeliel",
    title: "The Dispenser of Justice",
    description: "Angel of love, relationships, and divine justice. Seek for reconciliation.",
    domain: "Love, Justice",
    psalm: "Psalm 22:19",
    color: "#4ecdc4",
    symbol: "⚖️",
    invocationGuide: "1. Light a pink candle\n2. Hold a rose quartz in your left hand\n3. Say: 'Jeliel, Angel of Divine Love and Justice, I call upon your compassionate energy'\n4. Speak about the relationship or justice issue\n5. Ask: 'Heal the wounds and restore harmony'\n6. Visualize pink light surrounding all parties involved\n7. Thank Jeliel for the healing",
    evocationGuide: "Create a sacred space with rose petals and soft music. Sit comfortably and place rose quartz on your heart chakra. Visualize a beautiful rose garden where you meet Jeliel. The angel appears with scales of justice in one hand and a pink rose in the other. Feel the balance of love and justice flowing through you.",
    practicalUses: ["Healing relationships", "Resolving conflicts", "Finding true love", "Legal matters", "Forgiveness work"],
    meditationGuide: "Imagine yourself in a courtroom filled with soft pink light. Jeliel sits as the divine judge, but instead of punishment, only love and understanding emanate from this presence. Feel any anger or resentment in your heart being transformed into compassion. See all parties in your conflict surrounded by healing pink light.",
    offerings: ["Pink roses", "Rose water", "Love letters", "Acts of forgiveness"],
    timing: "Friday, Venus hours, Full moon",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "יליאל",
    planetaryCorrespondence: "Venus"
  },
  {
    id: 3,
    name: "Sitael",
    title: "The Protector",
    description: "Angel of protection and divine shelter. Call upon for safety and security.",
    domain: "Protection, Safety",
    psalm: "Psalm 91:1",
    color: "#1a535c",
    symbol: "🛡️",
    invocationGuide: "1. Light a blue candle\n2. Draw a protective circle with salt around yourself\n3. Say: 'Sitael, mighty protector, I call upon your shield of divine light'\n4. State what you need protection from\n5. Ask: 'Surround me with your impenetrable shield'\n6. Visualize blue armor of light covering your entire body\n7. Thank Sitael and keep the circle until ready",
    evocationGuide: "Stand in your sacred space wearing something blue. Visualize Sitael as a mighty warrior angel with a brilliant blue shield and sword of light. See the angel placing a protective bubble around you that nothing negative can penetrate. Feel completely safe and secure within this divine protection.",
    practicalUses: ["Physical protection", "Spiritual defense", "Home security", "Travel safety", "Protection from negativity"],
    meditationGuide: "Envision yourself standing in the center of a fortress made of brilliant blue light. Sitael stands guard at the gates, a majestic figure in blue armor. Feel the absolute safety and security this fortress provides. Know that no harm can reach you here, and this protection extends wherever you go.",
    offerings: ["Blue stones", "Salt", "Protective herbs (sage, rosemary)", "Shield imagery"],
    timing: "Tuesday, Mars hours, Dark moon",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "סיטאל",
    planetaryCorrespondence: "Mars"
  },
  {
    id: 4,
    name: "Elemiah",
    title: "The Divine Guardian",
    description: "Angel of spiritual protection and divine guidance in difficult times.",
    domain: "Protection, Guidance",
    psalm: "Psalm 6:4",
    color: "#9b59b6",
    symbol: "👁️",
    invocationGuide: "1. Light a purple candle\n2. Hold an amethyst crystal\n3. Say: 'Elemiah, Divine Guardian, I seek your spiritual protection and guidance'\n4. Describe the spiritual challenge you're facing\n5. Ask: 'Open my spiritual sight and guard my soul'\n6. Visualize a purple eye of protection opening in your third eye\n7. Thank Elemiah for the guidance",
    evocationGuide: "Meditate with amethyst on your third eye chakra. Visualize Elemiah as a tall figure with multiple eyes of different colors, each seeing different spiritual dimensions. Feel your own spiritual sight opening as the angel shares divine vision with you. See beyond the physical realm into the spiritual truth of your situation.",
    practicalUses: ["Spiritual protection", "Psychic defense", "Enhanced intuition", "Spiritual guidance", "Third eye opening"],
    meditationGuide: "Picture yourself in a temple made of amethyst crystal. In the center sits Elemiah, radiating purple light from a large eye in the center of their forehead. As you gaze into this divine eye, feel your own spiritual vision expanding. See the spiritual forces at work in your life and receive clear guidance.",
    offerings: ["Amethyst crystals", "Purple flowers", "Incense", "Written prayers"],
    timing: "Thursday, Jupiter hours, New moon",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "אלמיה",
    planetaryCorrespondence: "Jupiter"
  },
  {
    id: 5,
    name: "Mahasiah",
    title: "The Peaceful One",
    description: "Angel of peace and reconciliation. Brings harmony to relationships.",
    domain: "Peace, Harmony",
    psalm: "Psalm 34:4",
    color: "#3498db",
    symbol: "🕊️",
    invocationGuide: "1. Light a white candle\n2. Hold a white dove feather or image\n3. Say: 'Mahasiah, Angel of Divine Peace, I call upon your harmonizing energy'\n4. Speak about the conflict or unrest\n5. Ask: 'Bring peace to this situation and harmony to all involved'\n6. Visualize white doves flying around the situation, bringing peace\n7. Thank Mahasiah and blow out the candle gently",
    evocationGuide: "Find a quiet place in nature or create a peaceful environment with soft music. Visualize Mahasiah as a luminous being surrounded by white doves. Feel waves of peace emanating from the angel, washing over you and extending to all areas of conflict in your life. Let this peace settle deep into your soul.",
    practicalUses: ["Conflict resolution", "Inner peace", "Family harmony", "Workplace peace", "Calming anxiety"],
    meditationGuide: "Imagine yourself sitting by a still lake at sunset. The water perfectly reflects the peaceful sky. Mahasiah appears walking on the water towards you, leaving ripples of pure peace. As the angel approaches, feel all tension and conflict dissolving. Your heart becomes as still and peaceful as the lake.",
    offerings: ["White feathers", "Peace lilies", "Olive branches", "Calming music"],
    timing: "Sunday, Solar hours, Evening",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "מחסיה",
    planetaryCorrespondence: "Sun"
  },
  {
    id: 6,
    name: "Lelahel",
    title: "The Light of God",
    description: "Angel of healing and divine illumination. Brings clarity and understanding.",
    domain: "Healing, Illumination",
    psalm: "Psalm 9:11",
    color: "#f1c40f",
    symbol: "💡",
    invocationGuide: "1. Light a yellow candle\n2. Hold a clear quartz crystal\n3. Say: 'Lelahel, Divine Light, I call upon your illuminating presence'\n4. Ask for healing or clarity about specific issue\n5. Say: 'Shine your light upon this darkness and bring understanding'\n6. Visualize golden light filling your mind and body\n7. Thank Lelahel for the illumination",
    evocationGuide: "Sit in meditation with citrine or clear quartz. Visualize Lelahel as a being of pure golden light, with rays extending in all directions. See this light entering your crown chakra and illuminating every cell of your body, especially areas needing healing. Feel your understanding expanding as divine light fills your consciousness.",
    practicalUses: ["Physical healing", "Mental clarity", "Spiritual illumination", "Learning enhancement", "Depression relief"],
    meditationGuide: "Envision yourself in a cathedral made entirely of golden light. Lelahel stands at the altar, a figure so bright you can barely look directly at them. Golden rays of healing light stream from the angel towards you, penetrating every part of your being. Feel old wounds healing and new understanding dawning in your mind.",
    offerings: ["Yellow flowers", "Citrine crystals", "Candles", "Written questions seeking clarity"],
    timing: "Wednesday, Mercury hours, Midday",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "ללהאל",
    planetaryCorrespondence: "Mercury"
  },
  {
    id: 7,
    name: "Achaiah",
    title: "The Patient One",
    description: "Angel of patience and divine timing. Helps with understanding life's rhythms.",
    domain: "Patience, Divine Timing",
    psalm: "Psalm 103:8",
    color: "#2ecc71",
    symbol: "⏳",
    invocationGuide: "1. Light a green candle\n2. Hold an hourglass or watch\n3. Say: 'Achaiah, Angel of Divine Timing, I call upon your patient wisdom'\n4. Speak about what you're waiting for or struggling with\n5. Ask: 'Help me trust in divine timing and develop patience'\n6. Visualize time slowing down and becoming peaceful\n7. Thank Achaiah for the gift of patience",
    evocationGuide: "Sit quietly and focus on your breathing, making each breath slower and deeper than the last. Visualize Achaiah as an ancient, wise being surrounded by hourglasses and calendars. Feel the angel's patient energy flowing into you, teaching you that everything has its perfect timing in the divine plan.",
    practicalUses: ["Developing patience", "Trusting divine timing", "Reducing anxiety about future", "Finding peace in waiting", "Understanding life cycles"],
    meditationGuide: "Picture yourself in a vast library where Achaiah sits reading a book titled 'The Divine Timeline of Your Life.' As you approach, the angel smiles and shows you pages revealing how everything in your life has unfolded in perfect timing. Feel the deep trust that everything will happen when it's meant to.",
    offerings: ["Seeds", "Green plants", "Hourglasses", "Journals about patience"],
    timing: "Saturday, Saturn hours, Season changes",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "אכאיה",
    planetaryCorrespondence: "Saturn"
  },
  {
    id: 8,
    name: "Cahetel",
    title: "The Blessed One",
    description: "Angel of divine blessings and abundance. Brings prosperity and success.",
    domain: "Blessings, Abundance",
    psalm: "Psalm 95:6",
    color: "#e67e22",
    symbol: "🌟",
    invocationGuide: "1. Light a gold candle\n2. Place coins or symbols of abundance around it\n3. Say: 'Cahetel, Angel of Divine Blessings, I call upon your abundant grace'\n4. Express gratitude for current blessings\n5. Ask: 'Multiply these blessings and open new channels of abundance'\n6. Visualize golden rain falling upon you\n7. Thank Cahetel and share your blessings with others",
    evocationGuide: "Create an altar with items representing abundance (fruits, flowers, coins). Visualize Cahetel as a radiant being with hands full of golden light, pouring blessings upon you. Feel abundance flowing to you from all directions, and see yourself as a channel for blessings to flow to others.",
    practicalUses: ["Attracting abundance", "Career success", "Financial prosperity", "Manifesting goals", "Increasing gratitude"],
    meditationGuide: "Imagine standing in a golden wheat field under a sky full of stars. Each star represents a blessing in your life. Cahetel appears and waves their hand, causing the stars to rain down golden light upon the field. Watch as the wheat multiplies and grows, representing the abundance flowing into your life.",
    offerings: ["Gold items", "Fruits", "Flowers", "Gratitude lists"],
    timing: "Thursday, Jupiter hours, Waxing moon",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "כהתאל",
    planetaryCorrespondence: "Jupiter"
  },
  {
    id: 9,
    name: "Haziel",
    title: "The Vision of God",
    description: "Angel of divine mercy and forgiveness. Brings compassion and understanding.",
    domain: "Mercy, Forgiveness",
    psalm: "Psalm 25:6",
    color: "#e74c3c",
    symbol: "❤️",
    invocationGuide: "1. Light a red candle\n2. Hold your hands over your heart\n3. Say: 'Haziel, Angel of Divine Mercy, I call upon your compassionate love'\n4. Speak about what needs forgiveness (self or others)\n5. Ask: 'Fill my heart with your merciful love and help me forgive'\n6. Visualize red light healing your heart\n7. Thank Haziel and commit to acts of mercy",
    evocationGuide: "Place your hands on your heart and breathe deeply. Visualize Haziel as a being of pure love with a heart of ruby light. Feel the angel's merciful energy dissolving all resentment and filling your heart with divine compassion. See everyone who has hurt you surrounded by this same loving light.",
    practicalUses: ["Forgiveness work", "Healing emotional wounds", "Developing compassion", "Mercy for others", "Self-forgiveness"],
    meditationGuide: "Envision yourself in a garden of red roses where Haziel sits on a throne of rose petals. The angel's heart glows with ruby light that expands to encompass you. Feel all pain and resentment melting away as you're filled with pure, unconditional love. Understand that mercy is strength, not weakness.",
    offerings: ["Red roses", "Ruby or garnet stones", "Acts of mercy", "Forgiveness letters"],
    timing: "Friday, Venus hours, When moon is in Cancer",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "הזיאל",
    planetaryCorrespondence: "Venus"
  },
  {
    id: 10,
    name: "Aladiah",
    title: "The Hidden God",
    description: "Angel of divine grace and hidden wisdom. Reveals spiritual truths.",
    domain: "Grace, Hidden Wisdom",
    psalm: "Psalm 33:22",
    color: "#8e44ad",
    symbol: "🔮",
    invocationGuide: "1. Light a purple candle in a darkened room\n2. Hold a crystal ball or amethyst\n3. Say: 'Aladiah, Keeper of Hidden Wisdom, I call upon your revealing grace'\n4. Ask about the hidden truth or wisdom you seek\n5. Say: 'Unveil what is hidden and grant me divine understanding'\n6. Meditate in silence for at least 10 minutes\n7. Thank Aladiah for the revealed wisdom",
    evocationGuide: "Meditate in a dark room with only candlelight. Visualize Aladiah as a mysterious figure wrapped in violet robes, holding a book of secrets. As the angel opens the book, words of wisdom appear in your mind. Trust the insights that come, even if they seem unusual or unexpected.",
    practicalUses: ["Receiving hidden knowledge", "Understanding mysteries", "Developing intuition", "Spiritual revelations", "Uncovering truth"],
    meditationGuide: "Picture yourself in an ancient library filled with books containing the secrets of the universe. Aladiah appears as the librarian, leading you to a specific book meant just for you. As you open it, the pages reveal the hidden wisdom you've been seeking. Trust what you see and feel.",
    offerings: ["Purple candles", "Amethyst crystals", "Books", "Written questions"],
    timing: "Monday, Moon hours, Midnight",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "אלדיה",
    planetaryCorrespondence: "Moon"
  },
  {
    id: 11,
    name: "Lauviah",
    title: "The Praised One",
    description: "Angel of victory and triumph. Helps overcome obstacles and challenges.",
    domain: "Victory, Triumph",
    psalm: "Psalm 18:46",
    color: "#d35400",
    symbol: "🏆",
    invocationGuide: "1. Light an orange candle\n2. Hold a symbol of victory (trophy, crown, or sword)\n3. Say: 'Lauviah, Angel of Divine Victory, I call upon your triumphant power'\n4. Describe the challenge or obstacle you face\n5. Ask: 'Grant me the strength and strategy to overcome this challenge'\n6. Visualize yourself celebrating victory\n7. Thank Lauviah and take one action toward your goal",
    evocationGuide: "Stand with your arms raised in victory pose. Visualize Lauviah as a warrior angel with a golden sword and shield, leading an army of light. Feel the angel's victorious energy flowing into you, giving you courage and determination to face any challenge. See yourself already victorious.",
    practicalUses: ["Overcoming obstacles", "Winning competitions", "Achieving goals", "Building confidence", "Defeating negativity"],
    meditationGuide: "Imagine yourself on a mountaintop, having just climbed a difficult path. Lauviah stands beside you, placing a crown of light on your head. Look down at all the obstacles you've overcome and feel the satisfaction of victory. Know that with divine help, you can overcome anything.",
    offerings: ["Gold items", "Victory symbols", "Athletic equipment", "Success stories"],
    timing: "Tuesday, Mars hours, When facing challenges",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "לוויה",
    planetaryCorrespondence: "Mars"
  },
  {
    id: 12,
    name: "Hahaiah",
    title: "The Refuge",
    description: "Angel of refuge and divine shelter. Provides comfort in times of need.",
    domain: "Refuge, Divine Shelter",
    psalm: "Psalm 10:1",
    color: "#16a085",
    symbol: "🏠",
    invocationGuide: "1. Light a turquoise candle\n2. Create a comfortable, safe space around you\n3. Say: 'Hahaiah, Angel of Divine Refuge, I call upon your sheltering love'\n4. Speak about what you need refuge from\n5. Ask: 'Provide me sanctuary and comfort in this storm'\n6. Visualize yourself in a safe, warm sanctuary\n7. Thank Hahaiah and rest in the peace provided",
    evocationGuide: "Create a cozy nest with blankets and pillows. Visualize Hahaiah as a motherly figure opening her arms to embrace you. Feel yourself being enveloped in the warmest, safest hug you've ever experienced. Know that this divine refuge is always available to you, no matter what storms you face.",
    practicalUses: ["Finding emotional safety", "Recovering from trauma", "Creating sacred space", "Family protection", "Inner peace"],
    meditationGuide: "Picture yourself as a small child running home through a storm. You reach a beautiful house where Hahaiah waits with open arms at the door. Once inside, you're wrapped in a warm blanket by a glowing fireplace. Feel completely safe and loved, knowing this refuge is always available in your heart.",
    offerings: ["Comfort items", "Turquoise stones", "Home-baked goods", "Blankets for charity"],
    timing: "Monday, Moon hours, During difficult times",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "החיה",
    planetaryCorrespondence: "Moon"
  },
  {
    id: 13,
    name: "Iezalel",
    title: "The Praiser of God",
    description: "Angel of loyalty and friendship. Strengthens bonds and relationships.",
    domain: "Loyalty, Friendship",
    psalm: "Psalm 98:4",
    color: "#27ae60",
    symbol: "🤝",
    invocationGuide: "1. Light a green candle\n2. Hold hands with a friend or photo of loved ones\n3. Say: 'Iezalel, Angel of Divine Loyalty, I call upon your binding love'\n4. Express gratitude for friendships and relationships\n5. Ask: 'Strengthen these bonds and bring new loyal friends'\n6. Visualize golden threads connecting you to loved ones\n7. Thank Iezalel and reach out to a friend",
    evocationGuide: "Sit in a circle (real or imagined) with friends or loved ones. Visualize Iezalel at the center, weaving golden threads between all of you. Feel the strength of these connections and the angel's blessing on your relationships. Send love and loyalty to all in your circle.",
    practicalUses: ["Strengthening friendships", "Building loyalty", "Finding true friends", "Healing relationship rifts", "Creating community"],
    meditationGuide: "Envision yourself in a beautiful garden where all your friends and loved ones are gathered. Iezalel moves among you, sprinkling golden dust that makes the bonds between you glow with warm light. Feel the depth of connection and loyalty growing stronger with each person you see.",
    offerings: ["Friendship tokens", "Green plants", "Shared meals", "Letters to friends"],
    timing: "Wednesday, Mercury hours, Social gatherings",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "יזלאל",
    planetaryCorrespondence: "Mercury"
  },
  {
    id: 14,
    name: "Mebahel",
    title: "The Liberator",
    description: "Angel of justice and truth. Brings liberation from oppression.",
    domain: "Justice, Truth",
    psalm: "Psalm 9:9",
    color: "#2980b9",
    symbol: "🗽",
    invocationGuide: "1. Light a blue candle\n2. Hold chains, rope, or symbol of what binds you\n3. Say: 'Mebahel, Angel of Divine Liberation, I call upon your freeing power'\n4. Describe what you need liberation from\n5. Ask: 'Break these chains and set me free with divine justice'\n6. Visualize chains breaking and yourself flying free\n7. Thank Mebahel and take action toward freedom",
    evocationGuide: "Stand with your arms bound (symbolically with rope or ribbon), then have someone cut them free while you visualize Mebahel as a mighty angel with a sword of light, cutting through all that binds you. Feel the liberation flowing through your entire being as you're set free.",
    practicalUses: ["Breaking free from addictions", "Escaping toxic situations", "Fighting injustice", "Finding truth", "Personal liberation"],
    meditationGuide: "See yourself in a prison cell that represents whatever limits you. Mebahel appears with a key of pure light and opens the door. Step out into brilliant sunlight, feeling completely free. Watch as the prison dissolves, knowing you can never be truly imprisoned when you have divine support.",
    offerings: ["Broken chains", "Blue stones", "Justice symbols", "Freedom writings"],
    timing: "Saturday, Saturn hours, When seeking justice",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "מבהאל",
    planetaryCorrespondence: "Saturn"
  },
  {
    id: 15,
    name: "Hariel",
    title: "The Creator",
    description: "Angel of purification and renewal. Cleanses and renews the spirit.",
    domain: "Purification, Renewal",
    psalm: "Psalm 94:22",
    color: "#ecf0f1",
    symbol: "💧",
    invocationGuide: "1. Light a white candle near water\n2. Hold a bowl of pure water\n3. Say: 'Hariel, Angel of Divine Purification, I call upon your cleansing power'\n4. Speak about what needs to be cleansed or renewed\n5. Ask: 'Purify my spirit and renew my soul'\n6. Sprinkle water on yourself or drink some mindfully\n7. Thank Hariel for the cleansing",
    evocationGuide: "Take a ritual bath or shower, visualizing Hariel pouring pure white light over you that washes away all negativity, old patterns, and spiritual debris. Feel yourself being renewed and purified on all levels - physical, emotional, mental, and spiritual.",
    practicalUses: ["Spiritual cleansing", "Releasing old patterns", "Purifying space", "Emotional renewal", "Fresh starts"],
    meditationGuide: "Imagine standing under a waterfall of pure white light. As Hariel appears in the mist, feel the water washing away everything that no longer serves you. Emerge from the waterfall completely cleansed and renewed, like a newborn soul ready for fresh experiences.",
    offerings: ["Pure water", "White flowers", "Salt", "Cleansing herbs"],
    timing: "Monday, Moon hours, New moon",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "הריאל",
    planetaryCorrespondence: "Moon"
  },
  {
    id: 16,
    name: "Hekamiah",
    title: "The Establisher",
    description: "Angel of loyalty and devotion. Strengthens faith and commitment.",
    domain: "Loyalty, Devotion",
    psalm: "Psalm 88:1",
    color: "#34495e",
    symbol: "🔗",
    invocationGuide: "1. Light a silver candle\n2. Hold a symbol of commitment (ring, contract, promise)\n3. Say: 'Hekamiah, Angel of Divine Devotion, I call upon your steadfast power'\n4. Speak about your commitments and devotions\n5. Ask: 'Strengthen my resolve and deepen my loyalty'\n6. Visualize silver chains of light binding you to your highest path\n7. Thank Hekamiah and renew your commitments",
    evocationGuide: "Kneel in meditation and visualize Hekamiah as a solemn, dignified angel holding a silver cord. Feel this cord connecting you to the divine and to your highest commitments. Let the angel's steadfast energy strengthen your resolve and deepen your devotion to your spiritual path.",
    practicalUses: ["Strengthening commitments", "Deepening devotion", "Building discipline", "Loyal relationships", "Faith development"],
    meditationGuide: "Picture yourself making a sacred vow before Hekamiah in a temple of silver light. Feel the power of your commitment resonating through your entire being. See the angel blessing your devotion and surrounding you with the strength to maintain your promises through all challenges.",
    offerings: ["Silver items", "Written commitments", "Loyalty tokens", "Devotional practices"],
    timing: "Saturday, Saturn hours, When making commitments",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "הקמיה",
    planetaryCorrespondence: "Saturn"
  },
  {
    id: 17,
    name: "Lauviah II",
    title: "The Admirable",
    description: "Angel of revelation and spiritual insight. Brings divine revelations.",
    domain: "Revelation, Insight",
    psalm: "Psalm 8:1",
    color: "#9c88ff",
    symbol: "🌠",
    invocationGuide: "1. Light a violet candle under the stars\n2. Hold a piece of meteorite or star imagery\n3. Say: 'Lauviah, Angel of Divine Revelation, I call upon your illuminating wisdom'\n4. Ask for the specific revelation or insight you seek\n5. Say: 'Open the channels of divine communication'\n6. Meditate under the stars or starlit sky image\n7. Thank Lauviah for the revelations received",
    evocationGuide: "Go outside at night and look at the stars, or create a starry environment indoors. Visualize Lauviah as a cosmic angel made of starlight, downloading divine information directly into your consciousness. Be open to receiving insights in dreams, synchronicities, or sudden knowing.",
    practicalUses: ["Receiving divine revelations", "Understanding cosmic truths", "Prophetic dreams", "Spiritual insights", "Universal wisdom"],
    meditationGuide: "Float in space among the stars with Lauviah, an angel whose body is made of galaxies and nebulae. Feel your consciousness expanding to cosmic proportions as divine revelations flow into your awareness. Understand your place in the vast cosmic plan and receive the wisdom you've been seeking.",
    offerings: ["Star charts", "Meteorites", "Violet candles", "Dream journals"],
    timing: "Night hours, During meteor showers, Aquarius moon",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "לוויה",
    planetaryCorrespondence: "Uranus"
  },
  {
    id: 18,
    name: "Caliel",
    title: "The Swift to Help",
    description: "Angel of divine assistance and rapid help. Provides immediate aid.",
    domain: "Divine Assistance, Rapid Help",
    psalm: "Psalm 7:8",
    color: "#ff5722",
    symbol: "⚡",
    invocationGuide: "1. Light a red candle quickly\n2. Stand with urgency and purpose\n3. Say: 'Caliel, Angel of Swift Divine Aid, I call upon your immediate assistance'\n4. Clearly state your urgent need\n5. Ask: 'Come quickly with your divine help'\n6. Visualize lightning bringing instant solutions\n7. Thank Caliel and act immediately on any inspiration",
    evocationGuide: "In times of crisis or urgent need, call out to Caliel with complete faith. Visualize the angel as a lightning bolt of divine energy instantly arriving to provide exactly what you need. Feel the immediate shift in energy and circumstances as divine aid manifests.",
    practicalUses: ["Emergency situations", "Urgent needs", "Crisis intervention", "Immediate solutions", "Divine timing"],
    meditationGuide: "See yourself in a moment of great need, calling out to the heavens. Instantly, Caliel appears as a flash of lightning, bringing exactly what you require. Feel the relief and gratitude as divine assistance arrives at the perfect moment. Know this help is always available instantly.",
    offerings: ["Red candles", "Lightning imagery", "Urgent prayers", "Gratitude offerings"],
    timing: "Any time of urgent need, Storm hours, Emergency situations",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "כליאל",
    planetaryCorrespondence: "Mars"
  },
  {
    id: 19,
    name: "Leuviah",
    title: "The Hearing of God",
    description: "Angel of memory and intelligence. Enhances mental faculties.",
    domain: "Memory, Intelligence",
    psalm: "Psalm 40:1",
    color: "#607d8b",
    symbol: "🧠",
    invocationGuide: "1. Light a blue-gray candle\n2. Hold a book or symbol of learning\n3. Say: 'Leuviah, Angel of Divine Intelligence, I call upon your mental enhancement'\n4. Describe what you need to remember or understand\n5. Ask: 'Expand my memory and sharpen my intelligence'\n6. Visualize your brain glowing with divine light\n7. Thank Leuviah and begin your mental work",
    evocationGuide: "Sit in study position with books around you. Visualize Leuviah as a scholarly angel with multiple heads, each representing different aspects of intelligence. Feel divine knowledge flowing directly into your mind, enhancing your memory and understanding capabilities.",
    practicalUses: ["Studying for exams", "Improving memory", "Mental clarity", "Learning new skills", "Problem solving"],
    meditationGuide: "Imagine your brain as a vast library where Leuviah serves as the divine librarian. Watch as the angel organizes your memories, enhances your understanding, and creates new neural pathways for learning. Feel your intelligence expanding and your memory becoming crystal clear.",
    offerings: ["Books", "Study materials", "Brain-healthy foods", "Learning tools"],
    timing: "Wednesday, Mercury hours, Before studying",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "לוויה",
    planetaryCorrespondence: "Mercury"
  },
  {
    id: 20,
    name: "Pahaliah",
    title: "The Redeemer",
    description: "Angel of redemption and spiritual liberation. Frees from bondage.",
    domain: "Redemption, Liberation",
    psalm: "Psalm 120:1",
    color: "#795548",
    symbol: "🔓",
    invocationGuide: "1. Light a brown candle\n2. Hold a key or symbol of freedom\n3. Say: 'Pahaliah, Angel of Divine Redemption, I call upon your liberating grace'\n4. Confess what you need redemption from\n5. Ask: 'Free me from this bondage and grant spiritual liberation'\n6. Visualize chains falling away and light entering\n7. Thank Pahaliah and commit to your new freedom",
    evocationGuide: "In a moment of deep repentance and desire for change, visualize Pahaliah as an angel with keys to every lock that binds you. Feel the angel unlocking the chains of addiction, negative patterns, or spiritual bondage. Step into the light of redemption and new life.",
    practicalUses: ["Breaking addictions", "Spiritual redemption", "Freedom from guilt", "Pattern breaking", "Soul liberation"],
    meditationGuide: "See yourself in a prison of your own making, surrounded by the chains of old patterns and mistakes. Pahaliah appears with a golden key, unlocking every chain and opening the prison door. Step out into brilliant light, completely redeemed and free to begin anew.",
    offerings: ["Keys", "Freedom symbols", "Redemption writings", "Acts of service"],
    timing: "Sunday, Solar hours, During repentance",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "פהליה",
    planetaryCorrespondence: "Sun"
  },
  {
    id: 21,
    name: "Nelchael",
    title: "The Unique God",
    description: "Angel of learning and instruction. Helps with teaching and understanding.",
    domain: "Learning, Teaching",
    psalm: "Psalm 31:14",
    color: "#8b4513",
    symbol: "📚",
    invocationGuide: "1. Light a brown candle in your study space\n2. Hold your favorite book or learning material\n3. Say: 'Nelchael, Angel of Divine Learning, illuminate my mind'\n4. State what you wish to learn or teach\n5. Ask: 'Open my understanding and make me a vessel of wisdom'\n6. Visualize golden knowledge flowing into your mind\n7. Thank Nelchael and begin your studies",
    evocationGuide: "Sit surrounded by books and learning materials. Visualize Nelchael as a teacher angel with scrolls of wisdom. Feel the angel downloading knowledge directly into your consciousness, making complex subjects easy to understand.",
    practicalUses: ["Academic success", "Teaching abilities", "Understanding complex subjects", "Scholarly pursuits", "Wisdom acquisition"],
    meditationGuide: "Picture yourself in a cosmic classroom where Nelchael teaches the mysteries of the universe. Feel your mind expanding as divine knowledge fills every corner of your consciousness. Understanding flows easily and naturally.",
    offerings: ["Books", "Teaching materials", "Written knowledge", "Study notes"],
    timing: "Wednesday, Mercury hours, During study periods",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "נלכאל",
    planetaryCorrespondence: "Mercury"
  },
  {
    id: 22,
    name: "Yeiayel",
    title: "The Right Hand of God",
    description: "Angel of fame and fortune. Brings recognition and prosperity.",
    domain: "Fame, Fortune",
    psalm: "Psalm 121:5",
    color: "#ffd700",
    symbol: "👑",
    invocationGuide: "1. Light a golden candle at sunrise\n2. Hold something representing your talents\n3. Say: 'Yeiayel, Angel of Divine Recognition, I call upon your golden light'\n4. Describe your talents and aspirations\n5. Ask: 'Bring recognition to my gifts and prosperity to my endeavors'\n6. Visualize golden light surrounding your achievements\n7. Thank Yeiayel and take action toward your goals",
    evocationGuide: "Stand in sunlight or visualize golden light surrounding you. See Yeiayel as a regal angel placing a crown of light on your head, recognizing your divine talents and purposes. Feel your confidence growing as divine recognition flows to you.",
    practicalUses: ["Career advancement", "Public recognition", "Financial success", "Building reputation", "Achievement of goals"],
    meditationGuide: "Imagine yourself receiving an award for your achievements while Yeiayel stands beside you, blessing your success. Feel the joy of recognition and the responsibility that comes with your gifts. See your talents serving the highest good.",
    offerings: ["Gold items", "Achievement symbols", "Success stories", "Talent displays"],
    timing: "Sunday, Solar hours, During career pursuits",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "ייאיל",
    planetaryCorrespondence: "Sun"
  },
  {
    id: 23,
    name: "Melahel",
    title: "The Healing God",
    description: "Angel of healing waters and natural medicine. Brings physical healing.",
    domain: "Healing, Natural Medicine",
    psalm: "Psalm 121:8",
    color: "#00ced1",
    symbol: "🌊",
    invocationGuide: "1. Light a turquoise candle near water\n2. Hold healing herbs or crystals\n3. Say: 'Melahel, Angel of Divine Healing, I call upon your restorative power'\n4. Describe the healing needed\n5. Ask: 'Channel your healing energy through these sacred elements'\n6. Visualize healing blue-green light flowing through your body\n7. Thank Melahel and use the blessed items",
    evocationGuide: "Sit by natural water or hold a bowl of blessed water. Visualize Melahel as an angel of healing light, pouring divine medicine into the water. Feel the healing energy entering your body through every cell, restoring perfect health.",
    practicalUses: ["Physical healing", "Herbal medicine", "Water healing", "Health restoration", "Pain relief"],
    meditationGuide: "Imagine yourself in a healing temple by a sacred spring where Melahel ministers to the sick. Feel the angel's healing touch removing all illness and pain, restoring your body to perfect health and vitality.",
    offerings: ["Healing herbs", "Spring water", "Turquoise stones", "Health prayers"],
    timing: "Monday, Moon hours, Near water",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "מלהאל",
    planetaryCorrespondence: "Moon"
  },
  {
    id: 24,
    name: "Haheuiah",
    title: "The Good God",
    description: "Angel of protection from enemies and negative influences.",
    domain: "Protection, Defense",
    psalm: "Psalm 33:18",
    color: "#4b0082",
    symbol: "⚔️",
    invocationGuide: "1. Light an indigo candle in your protective space\n2. Hold a protective amulet or iron object\n3. Say: 'Haheuiah, Angel of Divine Protection, shield me from all harm'\n4. Name the threats or negative influences\n5. Ask: 'Surround me with your impenetrable defense'\n6. Visualize indigo armor protecting your entire being\n7. Thank Haheuiah and maintain your protective practices",
    evocationGuide: "Stand in a defensive posture and visualize Haheuiah as a warrior angel with a flaming sword, standing guard around you. Feel completely protected from all negative influences, knowing divine protection surrounds you always.",
    practicalUses: ["Protection from enemies", "Spiritual warfare", "Negative energy shielding", "Psychic defense", "Safety assurance"],
    meditationGuide: "See yourself surrounded by a fortress of indigo light where Haheuiah stands as your eternal guardian. No negative force can penetrate this divine protection. Feel safe and secure in all situations.",
    offerings: ["Protective stones", "Iron objects", "Defensive prayers", "Guardian imagery"],
    timing: "Tuesday, Mars hours, When feeling threatened",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "הההויה",
    planetaryCorrespondence: "Mars"
  },
  {
    id: 25,
    name: "Nith-Haiah",
    title: "The Giver of Wisdom",
    description: "Angel of divine wisdom and spiritual knowledge. Grants understanding.",
    domain: "Wisdom, Spiritual Knowledge",
    psalm: "Psalm 9:1",
    color: "#9370db",
    symbol: "🔯",
    invocationGuide: "1. Light a purple candle in meditation space\n2. Hold sacred texts or wisdom symbols\n3. Say: 'Nith-Haiah, Angel of Divine Wisdom, I seek your enlightenment'\n4. Ask for the wisdom or knowledge you need\n5. Say: 'Open my mind to divine understanding'\n6. Visualize purple light filling your third eye\n7. Thank Nith-Haiah and contemplate in silence",
    evocationGuide: "Meditate with sacred geometry or wisdom symbols. Visualize Nith-Haiah as an ancient angel holding the keys to all knowledge, unlocking the mysteries of existence within your consciousness.",
    practicalUses: ["Spiritual wisdom", "Divine knowledge", "Understanding mysteries", "Philosophical insight", "Sacred studies"],
    meditationGuide: "Enter a cosmic library where Nith-Haiah reveals the akashic records to you. Feel ancient wisdom flowing into your consciousness, answering questions you've carried for lifetimes.",
    offerings: ["Sacred texts", "Wisdom symbols", "Purple crystals", "Philosophical writings"],
    timing: "Thursday, Jupiter hours, During deep study",
    tradition: "Kabbalah",
    category: "Shem HaMephorash",
    hebrewName: "נתהיה",
    planetaryCorrespondence: "Jupiter"
  },
  {
    id: 73,
    name: "Michael",
    title: "Who is like God",
    description: "Archangel of protection, courage, and divine justice. Leader of God's army.",
    domain: "Protection, Justice, Courage",
    psalm: "Psalm 91",
    color: "#0000ff",
    symbol: "🗡️",
    invocationGuide: "1. Light a blue candle on Sunday\n2. Hold a sword or protective symbol\n3. Say: 'Archangel Michael, Defender of Light, I call upon your mighty protection'\n4. State what you need protection from\n5. Ask: 'Cut through all negativity with your sword of truth'\n6. Visualize blue flames surrounding you\n7. Thank Michael and feel his presence",
    evocationGuide: "Stand facing South, visualizing Michael as a towering warrior angel with blue flames and a sword of light. Feel his protective energy forming an impenetrable shield around you.",
    practicalUses: ["Ultimate protection", "Cutting negative cords", "Courage in conflict", "Justice issues", "Spiritual warfare"],
    meditationGuide: "See yourself standing with Michael on a battlefield of light, where all darkness is being vanquished. Feel his courage flowing through you, knowing you fight on the side of divine truth.",
    offerings: ["Blue candles", "Swords or knives", "Lapis lazuli", "Protection prayers"],
    timing: "Sunday, Solar hours, Times of danger",
    tradition: "Universal",
    category: "Archangel",
    hebrewName: "מיכאל",
    planetaryCorrespondence: "Sun"
  },
  {
    id: 74,
    name: "Gabriel",
    title: "God is my Strength",
    description: "Archangel of divine messages, creativity, and new beginnings. The divine messenger.",
    domain: "Messages, Creativity, Birth",
    psalm: "Psalm 23",
    color: "#ffffff",
    symbol: "📯",
    invocationGuide: "1. Light a white candle on Monday\n2. Hold a trumpet or message symbol\n3. Say: 'Archangel Gabriel, Divine Messenger, I open myself to your guidance'\n4. Ask for the message or guidance you need\n5. Say: 'Speak through me and to me with divine clarity'\n6. Visualize white light opening your throat chakra\n7. Thank Gabriel and listen for guidance",
    evocationGuide: "Face West during meditation, visualizing Gabriel as a radiant angel with white robes and a golden trumpet. Feel your intuitive and creative channels opening to divine inspiration.",
    practicalUses: ["Divine messages", "Creative inspiration", "Communication skills", "New beginnings", "Pregnancy and birth"],
    meditationGuide: "Stand in a field of white lilies where Gabriel appears with announcements of new life and possibilities. Feel your creative potential awakening as divine messages flow through you.",
    offerings: ["White lilies", "Trumpet music", "Creative works", "Written messages"],
    timing: "Monday, Moon hours, New moon",
    tradition: "Universal",
    category: "Archangel",
    hebrewName: "גבריאל",
    planetaryCorrespondence: "Moon"
  },
  {
    id: 75,
    name: "Raphael",
    title: "God has Healed",
    description: "Archangel of healing, travel, and divine love. The divine physician.",
    domain: "Healing, Travel, Medicine",
    psalm: "Psalm 103",
    color: "#00ff00",
    symbol: "🕊️",
    invocationGuide: "1. Light a green candle on Wednesday\n2. Hold healing herbs or medical symbols\n3. Say: 'Archangel Raphael, Divine Healer, I call upon your healing grace'\n4. Describe the healing needed (physical, emotional, or spiritual)\n5. Ask: 'Channel your healing light through me'\n6. Visualize green healing light filling your entire being\n7. Thank Raphael and trust in the healing process",
    evocationGuide: "Face East in meditation, visualizing Raphael as a luminous healer with green robes and a staff topped with a caduceus. Feel divine healing energy flowing through every cell of your body.",
    practicalUses: ["All forms of healing", "Safe travel", "Medical procedures", "Addiction recovery", "Emotional healing"],
    meditationGuide: "Enter a divine hospital where Raphael tends to all who suffer. Feel the angel's healing touch removing all pain and restoring perfect health to your body, mind, and spirit.",
    offerings: ["Green stones", "Healing herbs", "Medical supplies", "Travel prayers"],
    timing: "Wednesday, Mercury hours, During illness",
    tradition: "Universal",
    category: "Archangel",
    hebrewName: "רפאל",
    planetaryCorrespondence: "Mercury"
  },
  {
    id: 76,
    name: "Uriel",
    title: "Fire of God",
    description: "Archangel of divine wisdom, prophecy, and spiritual fire. Brings enlightenment.",
    domain: "Wisdom, Prophecy, Enlightenment",
    psalm: "Psalm 139",
    color: "#ff4500",
    symbol: "🔥",
    invocationGuide: "1. Light a red or orange candle on Tuesday\n2. Hold a flame symbol or ruby crystal\n3. Say: 'Archangel Uriel, Divine Fire, I call upon your enlightening wisdom'\n4. Ask for the wisdom or prophecy you seek\n5. Say: 'Kindle the flame of divine knowledge within me'\n6. Visualize flames of wisdom burning in your mind\n7. Thank Uriel and contemplate the revelations",
    evocationGuide: "Face North in meditation, visualizing Uriel as a majestic angel wielding divine fire that burns away ignorance and illuminates truth. Feel your consciousness expanding with divine wisdom.",
    practicalUses: ["Divine wisdom", "Prophecy", "Spiritual insight", "Truth revelation", "Enlightenment"],
    meditationGuide: "Stand before Uriel's throne of fire where the angel reveals the deepest mysteries of existence. Feel your soul being purified and enlightened by divine flames of wisdom.",
    offerings: ["Red candles", "Fire opals", "Ruby crystals", "Wisdom texts"],
    timing: "Tuesday, Mars hours, During seeking wisdom",
    tradition: "Universal",
    category: "Archangel",
    hebrewName: "אוריאל",
    planetaryCorrespondence: "Mars"
  },
  {
    id: 77,
    name: "Ariel",
    title: "Lion of God",
    description: "Angel of nature, animals, and environmental healing. Guardian of Earth.",
    domain: "Nature, Animals, Environment",
    psalm: "Psalm 104",
    color: "#228b22",
    symbol: "🦁",
    invocationGuide: "1. Light a green candle outdoors or near plants\n2. Hold a natural object (stone, leaf, crystal)\n3. Say: 'Ariel, Lion of God, I call upon your natural power'\n4. Express your connection to nature or animals\n5. Ask: 'Help me heal and protect the natural world'\n6. Visualize golden-green light connecting you to all life\n7. Thank Ariel and take environmental action",
    evocationGuide: "Meditate in nature or visualize yourself in a pristine wilderness where Ariel appears as a majestic lion-angel surrounded by all creatures in harmony. Feel your connection to all living things.",
    practicalUses: ["Animal healing", "Environmental protection", "Nature connection", "Earth magic", "Ecological balance"],
    meditationGuide: "Walk through a magical forest where Ariel leads you to understand your role as guardian of Earth. Feel the responsibility and joy of protecting all natural life.",
    offerings: ["Natural objects", "Plant seeds", "Animal care", "Environmental actions"],
    timing: "Earth seasons, During nature connection",
    tradition: "Universal",
    category: "Nature Angel",
    hebrewName: "אריאל",
    planetaryCorrespondence: "Earth"
  },
  {
    id: 78,
    name: "Chamuel",
    title: "He who sees God",
    description: "Angel of pure love, soulmates, and heart healing. Helps find lost things.",
    domain: "Love, Relationships, Finding",
    psalm: "Psalm 27",
    color: "#ff69b4",
    symbol: "💖",
    invocationGuide: "1. Light a pink candle on Friday\n2. Hold rose quartz or love symbol\n3. Say: 'Archangel Chamuel, Angel of Divine Love, I open my heart to you'\n4. Express your desires for love or what you've lost\n5. Ask: 'Help me find what I seek and heal my heart'\n6. Visualize pink light filling your heart chakra\n7. Thank Chamuel and trust in divine love",
    evocationGuide: "Meditate with your hand on your heart, visualizing Chamuel as a gentle angel surrounded by pink roses. Feel unconditional love flowing through your entire being, healing all wounds.",
    practicalUses: ["Finding soulmates", "Healing heartbreak", "Self-love", "Finding lost objects", "Relationship harmony"],
    meditationGuide: "Enter a garden of roses where Chamuel tends to hearts like flowers, nurturing each one to bloom in perfect love. Feel your heart opening to receive and give pure divine love.",
    offerings: ["Pink roses", "Rose quartz", "Love letters", "Heart symbols"],
    timing: "Friday, Venus hours, Matters of the heart",
    tradition: "Universal",
    category: "Love Angel",
    hebrewName: "כמואל",
    planetaryCorrespondence: "Venus"
  },
  {
    id: 79,
    name: "Zadkiel",
    title: "Righteousness of God",
    description: "Angel of mercy, forgiveness, and transformation. Helps with spiritual growth.",
    domain: "Mercy, Forgiveness, Transformation",
    psalm: "Psalm 51",
    color: "#9966cc",
    symbol: "🔮",
    invocationGuide: "1. Light a violet candle on Thursday\n2. Hold amethyst or purple crystal\n3. Say: 'Archangel Zadkiel, Angel of Divine Mercy, I seek your transforming grace'\n4. Confess what needs forgiveness or transformation\n5. Ask: 'Transform my pain into wisdom and my mistakes into growth'\n6. Visualize violet flame transmuting all negativity\n7. Thank Zadkiel and embrace the transformation",
    evocationGuide: "Visualize yourself surrounded by violet flames while Zadkiel appears with a golden chalice, transforming all your pain and mistakes into wisdom and spiritual growth.",
    practicalUses: ["Forgiveness work", "Spiritual transformation", "Alchemy of emotions", "Mercy and compassion", "Personal growth"],
    meditationGuide: "Step into Zadkiel's violet flame temple where all pain is transformed into wisdom, all mistakes into growth, and all suffering into compassion for others.",
    offerings: ["Amethyst crystals", "Violet candles", "Forgiveness rituals", "Transformation prayers"],
    timing: "Thursday, Jupiter hours, Times of growth",
    tradition: "Universal",
    category: "Transformation Angel",
    hebrewName: "צדקיאל",
    planetaryCorrespondence: "Jupiter"
  },
  {
    id: 80,
    name: "Raguel",
    title: "Friend of God",
    description: "Angel of divine justice and harmony. Brings balance and fairness.",
    domain: "Justice, Harmony, Balance",
    psalm: "Psalm 82",
    color: "#4169e1",
    symbol: "⚖️",
    invocationGuide: "1. Light a royal blue candle on Saturday\n2. Hold scales or justice symbol\n3. Say: 'Archangel Raguel, Friend of God, I call upon your divine justice'\n4. Describe the injustice or imbalance\n5. Ask: 'Restore divine order and bring fair resolution'\n6. Visualize blue light balancing all situations\n7. Thank Raguel and trust in divine justice",
    evocationGuide: "Visualize Raguel as a dignified angel holding golden scales, weighing all matters with perfect divine justice. Feel the peace that comes from knowing all will be made right.",
    practicalUses: ["Legal matters", "Workplace justice", "Relationship balance", "Fair treatment", "Divine order"],
    meditationGuide: "Stand in a cosmic courtroom where Raguel presides with perfect wisdom, ensuring that divine justice and harmony prevail in all situations.",
    offerings: ["Justice symbols", "Blue stones", "Balance items", "Fair treatment actions"],
    timing: "Saturday, Saturn hours, Legal matters",
    tradition: "Universal",
    category: "Justice Angel",
    hebrewName: "רגואל",
    planetaryCorrespondence: "Saturn"
  }
];

// Enhanced search and filtering utilities
export const getAngelsByCategory = (category: string): AngelEntity[] => {
  return angelicEntities.filter(angel => angel.category === category);
};

export const getAngelsByDomain = (domain: string): AngelEntity[] => {
  return angelicEntities.filter(angel => 
    angel.domain.toLowerCase().includes(domain.toLowerCase())
  );
};

export const getAngelsByTradition = (tradition: string): AngelEntity[] => {
  return angelicEntities.filter(angel => angel.tradition === tradition);
};

export const searchAngelsByNeed = (need: string): AngelEntity[] => {
  const searchTerm = need.toLowerCase();
  return angelicEntities.filter(angel =>
    angel.practicalUses.some(use => use.toLowerCase().includes(searchTerm)) ||
    angel.domain.toLowerCase().includes(searchTerm) ||
    angel.description.toLowerCase().includes(searchTerm)
  );
};

// Categories for filtering
export const angelCategories = [
  'Shem HaMephorash',
  'Archangel',
  'Healing Angel',
  'Protection Angel',
  'Love Angel',
  'Wisdom Angel',
  'Nature Angel',
  'Justice Angel',
  'Transformation Angel'
];

export const angelTraditions = [
  'Kabbalah',
  'Christian',
  'Islamic',
  'Universal',
  'New Age'
];
