// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zavecczituaopsluosdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdmVjY3ppdHVhb3BzbHVvc2RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjUwODYsImV4cCI6MjA2NjQwMTA4Nn0.Lv-IxTcxXLp_HfOmKLlYxIyHiXp5N0hOin3zY6FxrkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);