About
Contact
Test Fire Keeper// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvdvditqkkobagdmkivq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2ZHZkaXRxa2tvYmFnZG1raXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDMzODAsImV4cCI6MjA2ODA3OTM4MH0.6sy0n4ct8hgrPSii_Et7IYGEda1RUHpOIuENTLVof54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);